# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e9ff027fc3cb8d600204ed5b50434880"
name = "wishlist-test-app"
handle = "wishlist-test-app-4"
application_url = "https://catalogs-afford-chart-quilt.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-video-app-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://catalogs-afford-chart-quilt.trycloudflare.com/auth/callback",
  "https://catalogs-afford-chart-quilt.trycloudflare.com/auth/shopify/callback",
  "https://catalogs-afford-chart-quilt.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
